
package cxfDemo.myInterceptor.client.wsdemo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyInterceptorWSImplService", targetNamespace = "http://SEIImpl.myInterceptor.cxfDemo/", wsdlLocation = "http://localhost:8888/services/spring/myinterceptor/interceptorWS?Wsdl")
public class MyInterceptorWSImplService
    extends Service
{

    private final static URL MYINTERCEPTORWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cxfDemo.myInterceptor.client.wsdemo.MyInterceptorWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cxfDemo.myInterceptor.client.wsdemo.MyInterceptorWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/services/spring/myinterceptor/interceptorWS?Wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/services/spring/myinterceptor/interceptorWS?Wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYINTERCEPTORWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MyInterceptorWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyInterceptorWSImplService() {
        super(MYINTERCEPTORWSIMPLSERVICE_WSDL_LOCATION, new QName("http://SEIImpl.myInterceptor.cxfDemo/", "MyInterceptorWSImplService"));
    }

    /**
     * 
     * @return
     *     returns MyInterceptorWS
     */
    @WebEndpoint(name = "MyInterceptorWSImplPort")
    public MyInterceptorWS getMyInterceptorWSImplPort() {
        return super.getPort(new QName("http://SEIImpl.myInterceptor.cxfDemo/", "MyInterceptorWSImplPort"), MyInterceptorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyInterceptorWS
     */
    @WebEndpoint(name = "MyInterceptorWSImplPort")
    public MyInterceptorWS getMyInterceptorWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SEIImpl.myInterceptor.cxfDemo/", "MyInterceptorWSImplPort"), MyInterceptorWS.class, features);
    }

}
