
package webServices.base.client.demo2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SystemInfoImplService", targetNamespace = "http://serviceImpl.base.webServices/", wsdlLocation = "http://localhost:8080/J2EE/services/systeminfo?wsdl")
public class SystemInfoImplService
    extends Service
{

    private final static URL SYSTEMINFOIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webServices.base.client.demo2.SystemInfoImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webServices.base.client.demo2.SystemInfoImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/J2EE/services/systeminfo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/J2EE/services/systeminfo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYSTEMINFOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SystemInfoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemInfoImplService() {
        super(SYSTEMINFOIMPLSERVICE_WSDL_LOCATION, new QName("http://serviceImpl.base.webServices/", "SystemInfoImplService"));
    }

    /**
     * 
     * @return
     *     returns SystemInfo
     */
    @WebEndpoint(name = "SystemInfoImplPort")
    public SystemInfo getSystemInfoImplPort() {
        return super.getPort(new QName("http://serviceImpl.base.webServices/", "SystemInfoImplPort"), SystemInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemInfo
     */
    @WebEndpoint(name = "SystemInfoImplPort")
    public SystemInfo getSystemInfoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl.base.webServices/", "SystemInfoImplPort"), SystemInfo.class, features);
    }

}
