
package cxfDemo.JAXWS_DEMO01.client2.demo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "helloWSImplService", targetNamespace = "http://services.JAXWS_DEMO01.cxfDemo/", wsdlLocation = "http://localhost:8888/services/helloWS?Wsdl")
public class HelloWSImplService
    extends Service
{

    private final static URL HELLOWSIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cxfDemo.JAXWS_DEMO01.client2.demo.HelloWSImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cxfDemo.JAXWS_DEMO01.client2.demo.HelloWSImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/services/helloWS?Wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/services/helloWS?Wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSImplService() {
        super(HELLOWSIMPLSERVICE_WSDL_LOCATION, new QName("http://services.JAXWS_DEMO01.cxfDemo/", "helloWSImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "helloWSImplPort")
    public HelloWS getHelloWSImplPort() {
        return super.getPort(new QName("http://services.JAXWS_DEMO01.cxfDemo/", "helloWSImplPort"), HelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "helloWSImplPort")
    public HelloWS getHelloWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.JAXWS_DEMO01.cxfDemo/", "helloWSImplPort"), HelloWS.class, features);
    }

}
