
package cxfDemo.JAXWS_DEMO01.client2.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "helloWS", targetNamespace = "http://services.JAXWS_DEMO01.cxfDemo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWS {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://services.JAXWS_DEMO01.cxfDemo/", className = "cxfDemo.JAXWS_DEMO01.client2.demo.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://services.JAXWS_DEMO01.cxfDemo/", className = "cxfDemo.JAXWS_DEMO01.client2.demo.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
