
package webServices.cxf.client.demo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2014-07-05T13:56:00.484+08:00
 * Generated source version: 2.5.9
 * 
 */
public final class DataTypeWS_DataTypeWSImplePort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.serv.cxf.webServices/", "DataTypeWSImpleService");

    private DataTypeWS_DataTypeWSImplePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DataTypeWSImpleService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataTypeWSImpleService ss = new DataTypeWSImpleService(wsdlURL, SERVICE_NAME);
        DataTypeWS port = ss.getDataTypeWSImplePort();  
        
        {
        System.out.println("Invoking getStudentsMap...");
        webServices.cxf.client.demo.GetStudentsMapResponse.Return _getStudentsMap__return = port.getStudentsMap();
        System.out.println("getStudentsMap.result=" + _getStudentsMap__return);


        }
        {
        System.out.println("Invoking getStudentsList...");
        java.util.List<webServices.cxf.client.demo.Student> _getStudentsList__return = port.getStudentsList();
        System.out.println("getStudentsList.result=" + _getStudentsList__return);


        }
        {
        System.out.println("Invoking addStudent...");
        webServices.cxf.client.demo.Student _addStudent_arg0 = null;
        boolean _addStudent__return = port.addStudent(_addStudent_arg0);
        System.out.println("addStudent.result=" + _addStudent__return);


        }
        {
        System.out.println("Invoking getStudentById...");
        java.lang.Integer _getStudentById_arg0 = null;
        webServices.cxf.client.demo.Student _getStudentById__return = port.getStudentById(_getStudentById_arg0);
        System.out.println("getStudentById.result=" + _getStudentById__return);


        }

        System.exit(0);
    }

}
